### ISSUE TITLE
Using Varnish as front end?

### ISSUE THREAD

**Issue by hdavy2002** [dlundquist/sniproxy#150]
Is it possible. I have been trying things but no luck. I have Varnish on another vps and I am forwarding dns to varnish and then telling varnish to use sni as backend.

Varnish is listing on 192:168.1.22:80 (for example) and is configured to redirect to backend 192.168.1.23:80

SNI and DNS is on 192.168.1.23

Amazon.com goes to 192:168.1.22 and then gets forwarded to 192.168.1.23

Right now I am getting a message from varnish that backend now found.

But anyways, could a setup like this work. I want to cache images.

**Comment by dlundquist** [comment]
If Varnish includes a Hosts header in HTTP requests and a SNI extension in separate TLS for each host this sounds like it should work. I'm not entirely clear what your trying to accomplish, but if you route connections from Varnish to sniproxy and it includes those headers/extensions it should be able to forward to the connection to whatever backend you have configured. I'm not sure the benefit of including sniproxy is this configuration, since varnish must already parse the request and using sniproxy as a plain HTTP proxy seems unnecessary.
