### ISSUE TITLE
Request for further documentation/example configs

### ISSUE THREAD

**Issue by Copytalky** [dlundquist/sniproxy#151]
I love using SNIproxy but unfortunately don't always know the proper syntax or even exactly all the config type of options available to me. Would love to see a lot more well documented MAN pages created that could really make it clear as to how SNIproxy can be used/configured.

on a side note:So far I've yet to have to stray away from using SNIproxy, it seems to be rock solid stable and has yet to ever have crashed for me once I figured out proper configurations.

**Comment by dlundquist** [comment]
@Copytalky I agree the configuration documentation needs some improvement. I've been meaning to define a formal configuration grammar and move to a standard parser, but other issues have seemed more urgent. If you want to submit a PR to update the [man page][https://github.com/dlundquist/sniproxy/blob/master/man/sniproxy.8] I would be happy to consider it, the configuration grammar is defined https://github.com/dlundquist/sniproxy/blob/master/src/config.c#L63-L181 as a tree starting with the `global_grammar`.

I've been hesitant to make small iterations on the configuration parser, since I suspect there some configuration incompatibilities. The test suite includes `config_test` which parses a configuration and displays the parsed configuration, this can be used as an configuration lint test, although the input path is hard coded to `../sniproxy.conf`.

**Comment by dlundquist** [comment]
I've added a man page for the configuration in the 0.4.0 release: https://github.com/dlundquist/sniproxy/blob/0.4.0/man/sniproxy.conf.5

Questions, feedback, and further explanation is welcome.
