### ISSUE TITLE
IPv4 inbound to IPv6 outbound load balancing

### ISSUE THREAD

**Issue by phi0x** [dlundquist/sniproxy#157]
I'm trying to setup a IPv4 solution that will take requests from multiple inbound IPv4 addresses and then route the requests out IPv6 addresses. I believe there is no round-robin style feature in sniproxy as of yet. but I was wondering if at the very least, doing IPv4 inbound to IPv6 outbound is doable yet?

I have tried the following configuration with no success:

```
user daemon

error_log {
filename /tmp/sniproxy_error.log
priority debug
}

pidfile /var/tmp/sniproxy.pid
listen 80 {
proto http
source 2001:470:1f16:e6::2
access_log {
# Same options as error_log
filename /tmp/sniproxy_access.log
}

}
listen 443 {
proto tls
source 2001:470:1f16:e6::2
access_log {
# Same options as error_log
filename /tmp/sniproxy_access.log
}

}

table {
.*\\.* *

}
```

With the above config. sniproxy does listen on all interfaces, however when you enter 'source' it doesn't work since the 'source' address is not ipv6 but rather ipv4. In sniproxy configuration docs I saw the explanation for 'source' as follows:

"# Specify the source address for outgoing connections
    # This address must be configured on the host
    # NOTE: using this option prevents the operating system from selecting
    # and source address and port optimally and may significantly reduce the
    # maximum number of simultaneous connections possible.
    # Do not include a port in this address, otherwise you will be limited
    # to a single connection to each backend server."

as stated above it says to specify the source address for outgoing connections, which I have done.

What the result appears to be is: 'backend not available' when you test proxying. 

I have gotten ipv4 to ipv4 source addressing to work but I believe the 'source' command is not appropriate for my setup I've noted above.

Currently I have two scenario setups that are required of sniproxy:
- multiple ipv4 addresses on the host machine where users contacting the host machine via one of the ipv4 addresses gets proxied through that same source ipv4 address. so clients pointing to: 192.168.1.1 for web proxying, will also have 192.168.1.1 proxy via 192.168.1.1 outbound. (this configuration I've figured out and have working.). Also looking for a round robin feature for when a user talks to inbound IP 192.168.1.1, sniproxy chooses to send the transmission out the host machines 3 other available ipv4 addresses. IE. 192.168.1.2, 192.168.1.3, 192.168.1.4. Hence having 4 different outbound IP's to route from via round-robin.
- multiple ipv4 addresses on the host machine where users contacting the host machine via one of the ipv4 addresses gets proxied through a IPv6 address to contact a IPv6 compatible website. Also looking for a round robin feature for the available outbound IPv6 addresses.

I realize these features are not available yet but would love to see them as sniproxy so far has been exceptionally resource friendly. :)

**Comment by Copytalky** [comment]
I've also tried combining haproxy with sniproxy via the following configuration:
- haproxy setup to listen on 80/443 then pass via 81/444 from ipv4 to ipv6 local address(works).
- sniproxy listening on 81/444 on the ipv6 IP only. (works)
-sniproxy proxies and returns a webpage (works partially)
- - sniproxy still uses ipv4 outbound and renders the webpage via ipv4 even though it listens for HAproxy on ipv6.
- - tell sniproxy to use source address which is the incoming ipv6 address that haproxy points to, ends up resulting in 'backend unavailable.'

not sure why this is occurring. If I remove the 'source' parameter, it appears to accomplish the following path: ipv4 web request > haproxy listening on ipv4 > haproxy passes via tcp to ipv6 outbound > sniproxy listens for ipv6 > sniproxy takes ipv6 request and proxies it out ipv4.

i have iproute2 setup so that anything sourced from the ipv6 address, will go out the ipv6 gateway. 

I can get sniproxy alone to work with multiple ipv4 inbound/outbound addresses but I am trying to do ipv4 inbound to ipv6 outbound now, thus thought to accomplish this I had to use haproxy to first pass-through from ipv4 inbound to ipv6 outbound which sniproxy listens on.

any thoughts?

**Comment by Copytalky** [comment]
I've managed to make IPv4 to IPv6 work via the 'resolver' configuration in sniproxy along with haproxy routing in the request from IPv4 to IPv6 so that sniproxy picks up the request on the IPv6 interface so it can source it out the same IPv6 interface.

However there seems to be a few issues:

- proxied sites that are IPv6 compatible do not appear to work the same as when viewing on IPv4. For instance one site gives mixed results on geo-locations, while when viewing via IPv4 with sniproxy-alone it tunnels everything fine.

- IPv6 SSL doesn't appear to work always. IPv6 sites that have SSL state the SSL version is different sometimes. See chrome SSL error:
"A secure connection cannot be established because this site uses an unsupported protocol.
Error code: ERR_SSL_VERSION_OR_CIPHER_MISMATCH"

**Comment by dlundquist** [comment]
@Copytalky sorry for the late reply. The source directive doesn't work to specify the address family, the only way the address family can be specified is via the resolver mode (which you found) or by specifying the backend servers address explicitly. As you discovered the default resolver behavior is IPv4 only, this is to preserve compatibility with existing installations which depend on this behavior. The source directive is to control which address is used for multihomed hosts, but results in less efficient local outgoing socket allocation. Unless you need to control the outbound address it's best to not specify the source directive, and allow the Linux kernel to allocate the outbound socket address (IP and port) automatically.

Without detailed information how how the site works and access to logs, I don't have a way of knowing what happened on the site that gave a mix of geolocations. Perhaps data was transferred via cookies between an IPv4 only and IPv6 site?

I'm not sure why you need round robin for this configuration. If your selecting the backend server using DNS, sniproxy will connect to the first address returned in the DNS response, most DNS servers cycle through the record order to provide DNS round robin.

I haven't observed the ERR_SSL_VERSION_OR_CIPHER_MISMATCH error it could be a result of the larger IPv6 header, but I would expect the excess data to be buffered. A packet capture would reveal what is going on.

**Comment by Copytalky** [comment]
@dlundquist yes no worries! 

currently I prefer to let HAproxy or sniproxy do the managing of outbound IP routing due to some of my web clients utilizing hosts files. So this way I get to ensure they're round-robinning.

So I have it where HAproxy is there to manage the routing of packets from web-clients, then after the web-requests hit HAproxy, HAproxy roundrobins and chooses a sniproxy listener to send the web-request through.

with the built in resolver, when I select ipv6_first it allows me to engage my IPv6 addresses and I believe it falls back to the IPv4 when a uDNS lookup does not return a IPv6 DNS address?(If you could explain how that part of sniproxy works that would be great, as I don't fully understand that part yet I believe. Does it read URL headers then translate them into IPv4 OR IPv6 DNS requests via uDNS?)

I'm not sure on how to let linux round-robin through the outbound available IP's without doing the 'source' feature in sniproxy. If you know of a method I can look into please do let me know and I'll see if I can correct my configuration, as it sounds like my current setup is resource-heavy on sockets.

I've also noticed a few other bugs with my current setup.

current config:

```
user daemon

pidfile /var/tmp/sniproxy.pid

error_log {
    filename /tmp/sniproxy_error.log
    priority notice
}

resolver {
nameserver 8.8.8.8
mode ipv6_first
}
###############################################
listen 81 {
    proto http
        source 106.61.224.124
        table http
access_log {
        # Same options as error_log
        filename /tmp/sniproxy_access.log
priority debug
}
}
###############################################
listen 444 {
    proto tls
        table https
        source 106.61.224.124
access_log {
        # Same options as error_log
        filename /tmp/sniproxy_access.log
priority debug
}
}
###############################################
listen 82 {
    proto http
        source 2001:19f0:6400:87c3::64
        table http
access_log {
        # Same options as error_log
        filename /tmp/sniproxy_access.log
priority debug
}
}
###############################################
listen 445 {
    proto tls
        table https
        source 2001:19f0:6400:77c3::64
access_log {
        # Same options as error_log
        filename /tmp/sniproxy_access.log
}
}
###############################################
listen 83 {
    proto http
        source 2001:19f0:6400:77c3::65
        table http
access_log {
        # Same options as error_log
        filename /tmp/sniproxy_access.log
priority debug
}
}
###############################################
listen 446 {
    proto tls
        table https
        source 2001:19f0:6400:77c3::65
access_log {
        # Same options as error_log
        filename /tmp/sniproxy_access.log
priority debug
}
}
##############################################

table http{
.* *:80

}
table https{
.* *:443

}
```

websites produce in sniproxy_error.log the following errors now:
```
2015-03-20 04:40:47 bind failed: Invalid argument
2015-03-20 04:36:26 bind failed: Address family not supported by protocol
```
These two I'm seeing frequently as I'm browsing.

I dont know if it's due to maybe the packets that HAproxy is passing to sniproxy OR how sniproxy is using 'source' to force out IPv4 or IPv6 addresses after uDNS maybe resolves the address based on what inbound IP to sniproxy HAproxy passed to? IE. HAproxy passes inbound IPv4 web-request out via IPv4 to a sniproxy IPv4 listener which then does 'ipv6_first' while source is forced to a IPv4 address, uDNS see's the incoming is IPv4 but knows it should try IPv6 first and thus queries for IPv6 DNS AAAA records which when on outbound source IPv4 it maybe messes up?

If this is the problem, I may need to put in some sort of DNS64 or NAT64 solution? (and if this is the issue, it would be awesome to see this feature in future versions of sniproxy :)).

If you have any pointers for having me collect logs/debugging stuff I can most certainly try to collect it all and see what the results show us.

**Comment by dlundquist** [comment]
I used libudns when I introduced the nonblocking connect because ` gethostbyname()` was also blocking. Initially I only supported A (and CNAME) lookups to expedite the the release of the nonblokcing connect branch. Now I've tried to reimplement the `gethostbyname()` logic using libudns, there are four mode:

* `ipv4_only`: query for any A records, return the first A record returned (following CNAME records)
* `ipv6_only`: query for any AAAA records, return the first AAAA record returned (following CNAME records)
* `ipv4_first`: query for both A and AAAA records, wait for both queries to return, return the first A record if any, else return the first AAAA record
* `ipv6_first`: query for both A and AAAA records, wait for both queries to return, return the first AAAA record if any, else return the first A record

If no records are returned all of these will use the fallback address in the listener stanza if supplied.

Once an address is selected sniproxy attempts to connect to that address (`initiate_server_connect()`), first it creates a new socket using the address family of the backend or DNS query result, then if a source address is specified it attempts to bind to that address, otherwise we let the kernel automatically select ant outgoing address. The bind failed errors you are seeing are because the `ipv6_first` method you have selected can return either an IPv4 or IPv6 address, yet your are explicitly binding to an IPv6 address for the outgoing connection to the backend server. These options are mutually exclusive, you'll need to either using `ipv6_only` or allow the kernel to select an outgoing address automatically.

**Comment by Copytalky** [comment]
Thanks so much for the good explanation. this clears a lot of things up.

I tried to make a 'resolver' configuration based upon each listener. aka creating a listener and nesting resolver tags inside. This did not seem to work. I wanted to set each listener to their modes they support.

I ended up just setting the mode to ipv6_first and then creating just one listener and that appeared to utilize ipv6 when it was able to, I then had to do load balancing at the iptables level which I still have to tweak I think. currently I have packet based load balancing in affect instead of session based, not sure yet on if its doable to set iptables to rather load balance via sessions with one sniproxy listener.
