### ISSUE TITLE
reloading sniproxy configuration live feature

### ISSUE THREAD

**Issue by Copytalky** [dlundquist/sniproxy#162]
I'm wondering if there is a way currently or if it is planned or could be planned in future revisions for a feature where we can add/remove from the configuration file and have sniproxy re-scan the file and implement the changes on the fly when the config file has a change? Sniproxy would be listening to the system via something like the linux systems 'inotify'.

https://en.wikipedia.org/wiki/Inotify

Currently I have sites that I allow to be proxied via sniproxy and would like it where I could dynamically update the config file so that new users can be added, along with what table they're allowed to access that dictates which sites they can go to.

I've tried the command:
```
services sniproxy force-reload
```
which did not appear to work. Also I'm concerned if I do a restart, it will kill current user connections which would interrupt current users that are utilizing the proxying.

Any clarification on how it works currently would be appreciated and also if this feature might be considered for future revisions?

thanks!

**Comment by dlundquist** [comment]
This seems like a bit of a specialty feature, which I'm not sure would be widely portable. The way I would approach it would be to write another daemon in the scripting language of your choice that used inotify to monitor when the configuration file changed and send sniproxy a SIGHUP.
On Apr 14, 2015 6:16 PM, worlddev <notifications@github.com> wrote:I'm wondering if there is a way currently or if it is planned or could be planned in future revisions for a feature where we can add/remove from the configuration file and have sniproxy re-scan the file and implement the changes on the fly when the config file has a change? Sniproxy would be listening to the system via something like the linux systems 'inotify'.

https://en.wikipedia.org/wiki/Inotify

Currently I have sites that I allow to be proxied via sniproxy and would like it where I could dynamically update the config file so that new users can be added, along with what table they're allowed to access that dictates which sites they can go to.

I've tried the command:

services sniproxy force-reload


which did not appear to work. Also I'm concerned if I do a restart, it will kill current user connections which would interrupt current users that are utilizing the proxying.

Any clarification on how it works currently would be appreciated and also if this feature might be considered for future revisions?

thanks!

**Comment by Copytalky** [comment]
Thanks for the information. Would a SIGHUP cause sniproxy to reload without kicking current connections? Just wondering if there is a way I can make a script that will live reload sniproxy without killing connection sessions. I realize a users browser will retransmit packets if it isn't hearing back from sniproxy in a timely fashion which would then re-trigger sniproxy to go fetch the data, but thought it may add some unnecessary lag. Ideally it would be best for sniproxy to keep the connections/proxying working while it loads in new/removes configuration data.

**Comment by dlundquist** [comment]
Active connections are preserved across SIGHUP, there may be a brief delay as the new configuration is parsed and merged with the existing running config. This reload functionality includes adding and removing listeners and tables. If a listener is removed, existing connections are still preserved until they terminate normally, but no new connections are accepted. See `config_reload()`, `listeners_reload()` and `reload_tables()`.

**Comment by Copytalky** [comment]
thanks i'll see what I can do in the meantime. if this does come into future releases as stock that would be sweet! :) much appreciated for the work done so far with this project!
