### ISSUE TITLE
is it possible to route specific domains to specific servers?

### ISSUE THREAD

**Issue by chovy** [dlundquist/sniproxy#181]
For example site1.com gets routed through UK server and site2.com gets routed through Canadian server...while the DNS server itself is on a US based server?

**Comment by JonTheNiceGuy** [comment]
This is a DNS solution, rather than an SNIProxy solution. In your DNS records, site1.com will have an IP address in the UK, while site2 will have an IP address in Canada. The location of the DNS service doesn't matter

Now, if you're talking about hosting the services in those two countries, but exposing the internet facing end via a single IP address (perhaps you're thinking about some sort of disaster recovery situation?) Then, this might work, but I'd probably say that if you're the size where you have two locations for a given service, sniproxy probably isn't the right solution for you... But if you have more details that prove me wrong, if be glad to see what I can do to help!

**Comment by chovy** [comment]
I'm looking to develop a SmartDNS solution for my friends and family. The idea is certain domains get routed to specific servers via DNS to avoid blackouts.

**Comment by YYZviaYUL** [comment]
Chovy, this is what you're looking for: https://github.com/corporate-gadfly/Tunlr-Clone

Unfortunately, I'm having some issues with the the sniproxy portion not working correctly.

**Comment by dlundquist** [comment]
This appears to be a general question, and not an sniproxy specific issue. It appears to be answered, so I'm closing this issue.
