### ISSUE TITLE
Stopped working for netflix

### ISSUE THREAD

**Issue by davidcsi** [dlundquist/sniproxy#182]
Worked perfectly for me, a million thanks.
Only, it stopped working last night.... Netflix is blocking all proxied streaming... is there a way of having sniproxy also proxy the streaming and not only the http/https?
Thanks!

**Comment by lbdroid** [comment]
This is not a bug. The problem you are encountering is that the IP address of your server has been banned by netflix.

**Comment by davidcsi** [comment]
It's not the ip address, i changed to different ips on completely different networks... Still not working. I can still use the account from the US, though... They do something when you want to stream something...

**Comment by lbdroid** [comment]
Doesn't matter if you change from one blocked IP address to another. You'll still be blocked, and still blocked based on the IP address. They are currently blocking a LOT of different VPS services based on huge blocks of IP addresses.

If you want to bypass netflix geo-blocking, you will need an installation on a RESIDENTIAL internet connection, not a VPS service.

This thread should be closed, because it is off topic.

**Comment by rick5505** [comment]
I find it exactly on topic, since this is exactly what we are trying to use sniproxy for.

Perhaps, there could be a thread to inform people that the new Netflix policies are making these setups on VPS host are most likely going to fail. There are a lot of guides showing how to do this specifically for Netflix access through a VPS using sniproxy. 

So struggling to get it working will all be for nothing anyway.

**Comment by chovy** [comment]
@rick5505 what vps provider(s) are you using that are blocked?

**Comment by rick5505** [comment]
Hi chovy,
My VPS is SSD VPS. I am not saying I am blocked yet. I am struggling to get this sniproxy working. I suppose it is blocked, because if I use my OpenVPN to the same server I do get blocked. So that means it will not work for Netflix US access.

**Comment by lbdroid** [comment]
@rick5505 :
1) bypassing geo blocking on netflix is NOT the purpose of sniproxy.
2) your problems have NOTHING to do with sniproxy.

1+2 = this is OFF TOPIC.

**Comment by davidcsi** [comment]
chovy, I have a little cloud in a colocation in Miami, FL. this should work, but doesn't. I doubt they are blocking the whole of "America's Napt", but I will test on a friend's DSL.

Thanks

**Comment by chovy** [comment]
They've probably figured out a way to determine that some requests are proxied and some aren't. Try proxying everything.

**Comment by lbdroid** [comment]
Nope. Definitely not that. Geounblocking for netflix works FINE, as long as your IP address isn't blacklisted. I'm watching geounblocked USA netflix from Canada right now, and NOT proxying the CDN connection.

**Comment by daniel-lucio** [comment]
Im building a service geopeer.org based on  this. It is still in closed alpha testing. Just to let you know.

**Comment by chovy** [comment]
The problem is they are detecting that multiple accounts are coming through the same IP address....and if so blocking. The smartdns business is dying.

**Comment by daniel-lucio** [comment]
That's a half true. Yes, they are blocking ips, but the won't be able to block all residential block of Bell, Verizon, infinitum. It's like doing suicide.

**Comment by chovy** [comment]
who said anything about a block?

**Comment by daniel-lucio** [comment]
I miss read.

I doubt that, I mean, detecting more than one account from same IP is not a common scenario, but a valid one; here in Canada cable companies (and in Mexico as well) they do that, many users share a public IP (i have seen that in the cable, not dsl). 

But you are right, detecting multiple users coming from one IP it is a flag to pay attention and see who is the source.
