### ISSUE TITLE
any windows port?

### ISSUE THREAD

**Issue by daniel-lucio** [dlundquist/sniproxy#184]
does anyone has build a windows port?

**Comment by dlundquist** [comment]
I'm not aware of any Windows port, but since libev does support Windows it would be possible. Although libev under Windows is limited to select, so performance would suffer which a large number of sockets. I think the primary changes would involve changing over from integer file descriptors to socket pointers.

**Comment by LGA1150** [comment]
Running fine on Bash on Ubuntu on Windows 10.

**Comment by dlundquist** [comment]
I've also built and ran SNIproxy on the new Windows services for Linux, although the test cases due not pass do to edge cases in the Windows implementation of sockets. SNIproxy does seem to work on Windows services for Linux.
