### ISSUE TITLE
can i use http in addition to tls in 443?

### ISSUE THREAD

**Issue by chovy** [dlundquist/sniproxy#191]
```
listener 127.0.0.1:443 {
    protocol tls
    table TableName

    # Specify a server to use if the initial client request doesn't contain
    # a hostname
    fallback 192.0.2.5:443
}
```

My client doesn't support SNI, I'm wondering if I can add: `protocol https` or something to fix that in addition to `protocol tls`.

**Comment by dlundquist** [comment]
If the client does not include an SNI extension and uses either legacy SSL or TLS without SNI then there is no way for sniproxy to determine the hostname since the HTTP headers are encrypted. If you where wanting to handle both TLS and HTTP on the same port, this could be possible but would require a new protocol handler which detects if HTTP or TLS is being used and parses the connection accordingly.

**Comment by chovy** [comment]
sniproxy has this fallback url. what is that for? can I run haproxy there and handle it that way?

**Comment by lgrahl** [comment]
I've created a very crude `any` protocol which handles both `http` and `tls`. See: https://github.com/lgrahl/sniproxy/tree/protocol_any

It's not perfect as it would be better if the routing would depend on the detected protocol. But that would require changing the configuration file syntax...

**Comment by dlundquist** [comment]
@lgrahl I like that approach, but have some specific feedback on the implementation.

* The module named 'any' is rather ambiguous, 'try_each' or 'any_protocol' would be a more descriptive protocol/module than than 'any', 
* The for loop in `parse_any_header()` could be cleaned up, use either switch or if to determine the behavior based on the result of parse_packet not both.
* Changes in listener.c look good.
* `protocol->default_port` improvement reject configurations when no backend port is specified.
* How does protocol any avoid recurssively attempting to parse a packet with its own parse_packet function? I would suggest `if (protocols[i]>parse_packet == parse_any_header) break;` or such.
* Please compute the length from the constant array rather than integer constant when traversing protocols list, see https://github.com/dlundquist/sniproxy/blob/master/src/config.c#L427 for any example.
* I would like a better way to register protocols than include them in protocols.h. I would be okay with a global extern array of available protocols in `protocol.c`, this way any.c wouldn't need to directly depend on tls and http. I would like to find a way to build this array dynamically based on which modules are linked in, but I'm not aware of a way to do this.

**Comment by lgrahl** [comment]
Thanks for your feedback. It will probably take a bit of time until I can come back to it.
