### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by koala0529** [dlundquist/sniproxy#230]
你好，谢谢你开发的代码，尝试编译了一下，搭建成功了，大部分客户端都可以用，但是有些客户端会出现握手失败，提示使用的是sslv3，据说sslv3协议有设计缺陷，有些客户端就停用了；好像tlsv1.0以上版本也支持sni，能不能完善一下项目中的tls.c文件以做更好的支持？
ps：我是小白，如果有表达错误，请原谅。

**Comment by dlundquist** [comment]
I understand your problem is that sniproxy doesn't work for SSL 3.0 clients. Unfortunately it is not possible to detect the request hostname from SSL 3.0 ClientHello messages. You can use the `fallback` `listener` configuration to specify a single host to proxy all SSL 3.0 clients to, but without this request hostname sniproxy can not select which server to proxy to based on the hostname.

**Comment by koala0529** [comment]
@dlundquist thank for your replay,do as what you said, I have resloved my problem;
i just insert a `fallback` line into my config.
