### ISSUE TITLE
Support for Proxy Pass Arguments ??

### ISSUE THREAD

**Issue by OhmegaStar** [dlundquist/sniproxy#236]
Is is possible to support proxy pass features, so the receiver knows the eg. the ip the request came from ?

like these from a nginx config file:

                       proxy_set_header X-Real-IP  $remote_addr;
                        proxy_set_header X-Forwarded-For $remote_addr;
                        proxy_set_header Host $host;
                        proxy_pass http://192.168.0.71:8061;

Best Regards

OhmegaStar

**Comment by dlundquist** [comment]
@OhmegaStar sniproxy is strictly a layer 4 proxy, since it doesn't decrypt the TLS session it can not insert any data into the stream. This has been discussed before: #57, #124. If you're looking for application level (HTTP) manipulation you should look at HAproxy, Nginx, or Apache but you will need the TLS key and certificate on the proxy host to terminate the TLS session.

**Comment by OhmegaStar** [comment]
Aw damn... Thanks for clearing that up...
