### ISSUE TITLE
Using IPv6 only

### ISSUE THREAD

**Issue by ra84** [dlundquist/sniproxy#266]
Hello,
First thanks for the great work
I have a VPS with both IPv4 and IPv6 I want SNIProxy to only use IPv6, Is this possible?
Thnaks

**Comment by dlundquist** [comment]
SNIproxy can use IPv6 in all three places it opens remote sockets. The `listener` directive defaults to listening on the IPv6 any address '::', but on Linux this also accepts connections to any IPv4 address bound to the host. To listen on on IPv6 you will need to bind to specific IPv6 addresses. You can tweak this behavior system wide with /proc/sys/net/ipv6/bindv6only, but SNIproxy doesn't yet support configuring IPV6_V6ONLY on a per socket basis.

When establishing a connection to a backend server SNIproxy uses the address family specified in the table, or resulting from the DNS lookup. You can configure which addresses SNIproxy will listen for with the `resolver` `mode` directive, you will want the mode set to `ipv6_only` for an IPv6 only environment.

Finally there is the UDP socket for making DNS queries. This will use the address family of the nameserver. Although I recommend using a local DNS resolver since the single UDP socket for DNS queries is not the most robust against spoofed replies, please see comment in example config file.

**Comment by rami84** [comment]
Thanks, I will give this a try

**Comment by ra84** [comment]
Thanks. I will give this a try
