### ISSUE TITLE
Daemon crash after some time 

### ISSUE THREAD

**Issue by charithaka** [dlundquist/sniproxy#283]
Recently I've updated some of  sniproxy  versions with new sniproxy 5. but after few hours I'm getting alerts  due to sniproxy daemon automatically  stop without no reason. I've tested new version before deploy in production but  haven't found any issues. the same servers  which have massive load on SNI worked flawlessly with old version. 

Additional to the old config I mention resolver and resolve only  ipv4 on the configuration files. Is this can be a cause  or any impact on performance. And with this new update I update UDNS also. I'm using wildcard based dns resolving but I don't have any configured local caching DNS.

I suspect the log files also since those are huge files. 

My deployments are on centos 6.9 and I use init script to control the sniproxy daemon. can someone shed a light on this 

Thanks

**Comment by dlundquist** [comment]
@charithaka I'm sorry to hear you are have problems with a recent version of sniproxy. In order to troubleshoot this issue we will need to obtain some information from when the sniproxy daemon stops. My first suggestion would be to look at the error log after sniproxy stopped, it may have logged a message. Next I turn up the verbosity of the logs to debug. If this still doesn't reveal anything, I would enable core dumps so you can obtain a backtrace from the core file.

If you only have IPv4 connectivity, setting the resolver mode `ipv4_only` is the best option. It will be slightly faster than `ipv4_first` or `ipv6_first` since it doesn't need to wait for both queries to respond. Libudns hasn't had been updated in four years, so I don't think you need to update it. Although it is now often included as an distribution package, so if that is available I would use that rather than building libudns from source.

When you say the log files are huge, how large do you mean? Do you have log rotation configured? I would suggest rotating the log files be hand before, then starting sniproxy so it is easier to analyse the logs for any errors that could be related to your problems.

Sorry, I can't offer more specific suggestions.

**Comment by charithaka** [comment]
@dlundquist  thanks for the reply. found this is not because of the sniproxy. one of our internal team member running crontabs for some tasks and accidentally put SNI under it. since old conf file have underscore on it process failing to start. I'm extremely sorry for asking question without checking properly. please remove this issue. 

Finally thanks for this wonderful piece of software !! excellent job !!
