### ISSUE TITLE
PPA update please?

### ISSUE THREAD

**Issue by BloodyIron** [dlundquist/sniproxy#285]
Any chance we can get the PPA ( https://launchpad.net/~dlundquist/+archive/ubuntu/sniproxy ) to have 0.5.0 please? I know it's been out a while now. ;)

**Comment by dlundquist** [comment]
Yeah, I can update that, I didn't know anyone was still using it. What release of Ubuntu are you using, if I recall I have to push each release separately. Also, it looks like I need to update my GPG on launchpad. I'm inclined to push 0.5.0-51-g7c8612 since it includes SO_REUSEPORT, ipv6_only, and proxy_header support along with several bug fixes.

As the one representative of users using my PPA, which version would prefer and for what release?

**Comment by BloodyIron** [comment]
Well, namely interested in 16.04 for this.
