### ISSUE TITLE
Domain based VPN Gateway/Proxy for all devices

### ISSUE THREAD

**Issue by mrahmadt** [dlundquist/sniproxy#304]
Hi

I would like to share with you a project that I created to set up and manage a VPN gateway/proxy to reroute specific internet domains requests to go through a VPN tunnel.

I'm using sniproxy to reroute which domains I want them to go through a VPN tunnel.

Check it out and let me know what do you think about it.

https://github.com/mrahmadt/SmartGW

**Comment by dlundquist** [comment]
Looks like a useful way to manage this type of split tunnel VPN
arrangement. Since you are not specifying any DAEMON_ARGS you don't need to
uncomment it from /etc/default/sniproxy. You might consider calling out who
operates the DNS servers 208.67.222.222 and 208.67.222.220, since this
provider has the potential to insert more of this type of traffic
re-routing. As with the choice of NordVPN the user is trusting this
upstream DNS provider and any intermediate network service providers not to
intercept and reroute their traffic.

-Dustin

**Comment by mrahmadt** [comment]
Thanks @dlundquist for your suggestion and feedback, I already change the DNS upstream to NordVPN
