### ISSUE TITLE
Chromecast issues

### ISSUE THREAD

**Issue by fniephaus** [dlundquist/sniproxy#64]
I have tried to find out why Chromecast does not work with your sniproxy. I don't understand why, but it looks like the proxy sends "Change Cipher Spec" packets after the "Server Key Exchange" which results in Chromecast sending a new (SSL 3.0) "Client Hello".

**Successful connection:**
![1](https://f.cloud.github.com/assets/2368856/2166649/f9488000-9509-11e3-957d-612720c450e4.png)

**Unsuccessful connection via sniproxy:**
![2](https://f.cloud.github.com/assets/2368856/2166650/fd88c36e-9509-11e3-8c9f-b13a8f1bad10.png)

Any idea how to deal with this?

**Comment by lbdroid** [comment]
I don't know if there was a change on the chromecast side, but I can say with authority that chromecast *does* (at least now) work with SNI. While I haven't actually tested sniproxy, I have with haproxy, using exclusively SNI configuration, and works perfectly.

I.e. on local openwrt iptables;
iptables -t nat -A PREROUTING -d 8.8.8.8 -j DNAT --to-destination 192.168.1.1
iptables -t nat -A PREROUTING -d 8.8.4.4 -j DNAT --to-destination 192.168.1.1
iptables -t nat -A PREROUTING -p tcp --dport 80 -d 192.168.10.10 -j DNAT --to-destination my.remote.ip.address:27200
iptables -t nat -A POSTROUTING -p tcp --dport 27200 -j MASQUERADE
iptables -t nat -A PREROUTING -p tcp --dport 443 -d 192.168.10.10 -j DNAT --to-destination my.remote.ip.address:27201
iptables -t nat -A POSTROUTING -p tcp --dport 27201 -j MASQUERADE

On local openwrt dnsmasq, whole bunch of;
address=/domain.name/192.168.10.10

On *remote* openwrt iptables (just to implement quick and dirty access restriction);
iptables -I zone_wan_input -p tcp -m tcp -s my.local.ip.address --dport 27200:27201 -j ACCEPT

And of course, a corresponding haproxy.cfg on the remote openwrt.

Since it works with haproxy, it should also work with sniproxy, unless there is something broken or unimplemented in sniproxy that is required.

I would suggest that if anyone is interested in getting sniproxy working with chromecast, they should test again now, to see if the real problem has somewhere been resolved, and *if not*, there may be some work needed here.
